### ISSUE TITLE
インデントのみの空白行にもエラーを出す

### ISSUE THREAD

**Issue by ysakmrkm** [ysakmrkm/grunt-sass-format#5]
``` css
.hoge {
    margin:0 auto;
    <=ここにインデントあり
    .fuga {
        display:block;
    }
}
```
