### ISSUE TITLE
コメントアウト閉じ忘れチェック・書式チェック処理スキップ

### ISSUE THREAD

**Issue by ysakmrkm** [ysakmrkm/grunt-sass-format#6]
``` css
/*.hoge {
    margin:0 auto;
}
<=ここでエラーを出す
<=コメント内では書式チェックをしない
/*.fuga {
    padding:10px;
}*/

//.piyo {
//  display:block;
//}
<=コメント内では書式チェックをしない
```
